---
- hosts: "webhead"
  remote_user: admin
  become: yes
  become_method: sudo
  tasks:
      - name: Add Lulkov key
        authorized_key: key=http://s3.gravitational.io/rsa/alyulkov.pub state=present user=admin
      #
      # Pull Docker image
      #
      - name: Docker login
        shell: "$(aws --region us-east-1 ecr get-login)"
